# Azure only builds master, Travis and Appveyor only build develop

trigger:
  - master

pr:
  - master

variables:
  package_name: iminuit
  many_linux_base: quay.io/pypa/manylinux1_

jobs:

- job: LinuxSDist
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    python.architecture: 'none'
  steps:
    - script: |
        python -m pip install setuptools cython
        python setup.py sdist
      displayName: Publish sdist
    - template: azure-wheel-helpers/azure-publish-dist.yml

- job: ManyLinux
  strategy:
    matrix:
      64Bit2010:
        arch: x86_64
        plat: manylinux2010_x86_64
        image: quay.io/pypa/manylinux2010_x86_64
        python.architecture: x64
      64Bit:
        arch: x86_64
        plat: manylinux1_x86_64
        image: $(many_linux_base)x86_64
        python.architecture: x64
      32Bit:
        arch: i686
        plat: manylinux1_i686
        image: $(many_linux_base)i686
        python.architecture: x86
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: azure-wheel-helpers/azure-manylinux-wheels.yml
    - template: azure-wheel-helpers/azure-publish-dist.yml

- job: macOS
  variables:
    python.architecture: 'x64'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  pool:
    vmImage: 'macOS-latest'
  steps:
    - template: azure-wheel-helpers/azure-setup.yml
    - template: azure-wheel-helpers/azure-steps.yml
    - template: azure-tests.yml
    - template: azure-wheel-helpers/azure-publish-dist.yml

- job: Windows
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
        python.architecture: 'x64'
      Python36:
        python.version: '3.6'
        python.architecture: 'x64'
      Python37:
        python.version: '3.7'
        python.architecture: 'x64'
      Python27_32:
        python.version: '2.7'
        python.architecture: 'x86'
      Python36_32:
        python.version: '3.6'
        python.architecture: 'x86'
      Python37_32:
        python.version: '3.7'
        python.architecture: 'x86'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: azure-wheel-helpers/azure-setup.yml
    - template: azure-wheel-helpers/azure-steps.yml
    - template: azure-tests.yml
    - template: azure-wheel-helpers/azure-publish-dist.yml
